-- 왜 틀리나 했는데 중복된 값이 있다는 것을 간과하고 있었다.
SELECT A.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT) AS TOTAL_SALES FROM FOOD_PRODUCT AS A 
JOIN FOOD_ORDER AS B ON A.PRODUCT_ID=B.PRODUCT_ID
WHERE YEAR(B.PRODUCE_DATE)='2022' AND MONTH(B.PRODUCE_DATE)='05'
GROUP BY A.PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC; 
