SELECT CAR_ID, IF (CAR_ID IN (
    -- 서브 쿼리 (특정 날짜에 대여중인 차량 ID)
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
), '대여중', '대여 가능') AS AVAILABILTY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;

-- ALTER 없이 어떤 열을 만드는 법: IF(조건문(서브쿼리 포함 가능), 'TRUE일때 값', 'FALSE'일때 값') AS 이름
