SELECT A.WRITER_ID AS USER_ID, B.NICKNAME, SUM(PRICE) AS TOTAL_SALES FROM USED_GOODS_BOARD AS A 
JOIN USED_GOODS_USER AS B ON A.WRITER_ID=B.USER_ID
WHERE STATUS='DONE'
GROUP BY A.WRITER_ID, B.NICKNAME
-- HAVING은 GROUP BY다음에 적어야 한다.
-- SUM등의 함수와 관련된 것들은 HAVING과 함께 적어야 한다.
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;
