-- 프로그래머스 SUM, MAX, MIN문 연습 10번

--정답:
SELECT CAST(DATE_FORMAT(DIFFERENTIATION_DATE, '%Y') AS YEAR) AS YEAR, 
(SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA WHERE DATE_FORMAT(DIFFERENTIATION_DATE, '%Y')=YEAR) - SIZE_OF_COLONY AS YEAR_DEV,
ID
FROM ECOLI_DATA
ORDER BY YEAR ASC, YEAR_DEV ASC;

--DATETIME형의 형식 바꾸기: DATE_FORMAT(data, form) -> 형변환(DATETIME -> INTEGER): CAST(data AS YEAR)
---> 이때, CAST 사용시 INTEGER로 바꾸면 오류 발생하므로 YEAR형으로 바꿔주자.
