SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
    -- 서브 쿼리 (음식 타입, 즐겨찾기수)
    SELECT FOOD_TYPE, MAX(FAVORITES) FROM REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;
