SELECT ITEM_ID, ITEM_NAME, RARITY FROM ITEM_INFO
WHERE ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL GROUP BY PARENT_ITEM_ID)
ORDER BY ITEM_ID DESC;

-- 어디에 없다 = NOT IN
-- IN 사용할 때 NULL값이 있으면 의도치 않은 값이 나올 수 있으니 제거해 준다.
